### ISSUE TITLE
How many classes did you use in HRSC2016 dataset?

### ISSUE THREAD

**Issue by yijingru** [dingjiansw101/RoITransformer_DOTA#27]
Hi, I have a question about the HRSC categories. You claimed 20 categories of HRSC2016 in the CVPR paper, however, in your code hrsc.py, it seems you only use ship class,

        self.classes = ['__background__',  # always index 0
                        'ship']
So did you only use the ship class? I have this question because the original data seems to have 28 categories.

**Comment by dingjiansw101** [comment]
HRSC2016 has three levels of tasks, corresponding to different categories. In our experiments, we only conduct experiments for one class.

**Comment by yijingru** [comment]
Thanks!
